<?php if($_imageUrl=$this->getCurrentCategory()->getImageUrl()): ?>
        <p class="category-image"><img src="<?php echo $_imageUrl ?>" alt="<?php echo $this->htmlEscape($this->getCurrentCategory()->getName()) ?>" /></p>

<?php echo $this->htmlEscape($this->getCurrentCategory()->getName()) ?><br>

<?php echo $this->htmlEscape($this->getCurrentCategory()->getDescription()) ?>

    <?php endif; ?>


test