<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="blog-title page-head">
	<h1><?php echo Mage::getStoreConfig('blog/blog/title'); ?></h1>
</div>
<?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
	    <?php if ($post->getImage()) : list($width, $height, $type, $attr) = getimagesize(Mage::getBaseUrl('media'). $post->getImage()); ?>
		<div class="blog-img-wrap">
			<a class="blog-img-link-hover" href="<?php echo $post->getAddress(); ?>"></a>
			<a class="blog-img-link" href="<?php echo $post->getAddress(); ?>">
				<img <?php echo $attr; ?> class="blog-img" src="<?php echo Mage::getBaseUrl('media') . $post->getImage(); ?>" <?php echo ($post->getImageRetina() ? 'data-srcX2="'.Mage::getBaseUrl('media') . $post->getImageRetina().'"' : '' ); ?>>
			</a>
		</div>
	    <?php endif; ?>
		<div class="blogMeta">
			<div class="blog-icon">
				<div class="inner">
					<?php if ($this->getCommentsEnabled() && $post->getCommentCount() != ''): ?>
						<a href="<?php echo $post->getAddress(); ?>#commentBox" class="blog-comments"><?php echo $post->getCommentCount(); ?></a>
					<?php endif; ?>
				</div>
			</div>
			<div class="postDetails">
				<?php $postCats = $post->getCats(); ?>
				<?php if (!empty($postCats)): ?>
					<?php echo Mage::helper('blog')->__('Posted in'); ?>
					<?php foreach ($postCats as $data): ?>
						<a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
					<?php endforeach; ?>
				<?php else: ?>
				<?php endif; ?><?php echo '<span class="author">'. $this->__("By"); ?> <?php echo $post->getUser().'</span>'. ' ' . '<span class="separator-resp">|</span>'; ?>
				<?php 
				$t = strtotime($post->getOrigData('created_time'));
				echo '<span class="month">'.date('F', $t).'</span>'. ' ' .'<span class="day">'.date('d', $t).'</span>'. ', ' .'<span class="year">'.date('Y', $t).'</span>';
				?>
				<?php if ($this->getCommentsEnabled()): ?>
					<span class="commentBox">
						<span class="separator-resp">| </span><a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo ($post->getCommentCount() !=0) ? $post->getCommentCount() : '0'; ?> Comments</a>
					</span>
				<?php endif; ?>
			</div>
		</div>
		<div class="postContentWrapper">	
			<div class="postTitle">				
				<h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
			</div>
			<div class="postContent std"><?php echo $post->getPostContent(); ?></div>
			<?php //echo $this->getBookmarkHtml($post) ?>
			<!--<div class="tags"><?php //echo $this->getTagsHtml($post) ?></div>-->
		 </div>		
    </div>
<?php endforeach; ?>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>