<?php
/**
 * Nybohansen ApS
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * We do not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * In case of incorrect edition usage, we don't provide support.
 * =================================================================
 *
 * @category   Nybohansen
 * @package    Nybohansen_Pacsoft
 * @copyright  Copyright (c) 2014 Nybohansen ApS
 * @license    LICENSE.txt
 */
?>

<?php foreach ($this->getAddons() as $code => $addon): ?>
    <?php if($addon['checked']): ?>
        <input type="checkbox" name="addons[]" value="<?php echo $code; ?>" checked/> <label for="<?php echo $code; ?>" class="normal"><?php echo $addon['desc']; ?></label><br />
    <?php else: ?>
        <input type="checkbox" name="addons[]" value="<?php echo $code; ?>" /> <label for="<?php echo $code; ?>" class="normal"><?php echo $addon['desc']; ?></label><br />
    <?php endif?>
<?php endforeach; ?>


