<?php
/**
 * Nybohansen ApS
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * We do not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * In case of incorrect edition usage, we don't provide support.
 * =================================================================
 *
 * @category   Nybohansen
 * @package    Nybohansen_Pacsoft
 * @copyright  Copyright (c) 2014 Nybohansen ApS
 * @license    LICENSE.txt
 */
?>

<?php if(!count($this->getServicePoints())): ?>
    <?php echo $this->__('No parcel shops in this zip'); ?>
<?php else: ?>

    <?php
    $innerHtml = '';
    foreach ($this->getServicePoints() as $servicePoint){
        $servicePointId = $servicePoint->servicePointId;
        $name = ucwords(strtolower($servicePoint->name));
        $address = ucwords(strtolower($servicePoint->visitingAddress->streetName)).' '.$servicePoint->visitingAddress->streetNumber;
        $zip = $servicePoint->visitingAddress->postalCode;
        $city = $servicePoint->visitingAddress->city;

        if($this->getDisplayType() == 'select'){
            $innerHtml .= '<option '.($this->getPickupId() == $servicePointId ? 'selected' : '').' value="'.$servicePointId.'">'.$name.' · '.$address.' · '.$zip.' · '.$city.'</option>';
        }
    }
    ?>

    <select class="" name="PUPOPT[servicePointId]">
        <?php echo $innerHtml;?>
    </select>

<?php endif; ?>
