<?php
/**
 * Category view template
 *
 * @see Queldorei_Priceslider_Block_Mainslider
 */
?>
<?php
$_helper    = $this->helper('catalog/output');
$_category  = $this->getCurrentCategory();
$_imgHtml   = '';
if ($_imgUrl = $_category->getImageUrl()) {
    $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
    $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
}
?>
<div class="page-title category-title">
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>


<?php if($this->isContentMode()): ?>
<?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
<p class="category-image">
    <?php echo $this->getCmsBlockHtml() ?>
</p>
<?php echo $this->getProductListHtml() ?>

<?php else: ?>
<?php echo $this->getProductListHtml() ?>

<?php endif; ?>